/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package giocotris;

/**
 *
 * @author Niccolo'
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        UnoVsUno.setContentAreaFilled(false);
        UnoVsUno.setBorderPainted(false);   
        UnoVsPc.setContentAreaFilled(false);
        UnoVsPc.setBorderPainted(false);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Setting = new javax.swing.JButton();
        UnoVsPc = new javax.swing.JButton();
        UnoVsUno = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Setting.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        Setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocotris/settings.png"))); // NOI18N
        Setting.setText("Setting");
        Setting.setBorderPainted(false);
        Setting.setContentAreaFilled(false);
        Setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingActionPerformed(evt);
            }
        });
        getContentPane().add(Setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 270, 30));

        UnoVsPc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocotris/robot.png"))); // NOI18N
        UnoVsPc.setText("vs");
        UnoVsPc.setToolTipText("");
        UnoVsPc.setBorderPainted(false);
        UnoVsPc.setContentAreaFilled(false);
        UnoVsPc.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        UnoVsPc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnoVsPcActionPerformed(evt);
            }
        });
        getContentPane().add(UnoVsPc, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 270, 30));

        UnoVsUno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocotris/people.png"))); // NOI18N
        UnoVsUno.setText("vs");
        UnoVsUno.setBorderPainted(false);
        UnoVsUno.setContentAreaFilled(false);
        UnoVsUno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UnoVsUno.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        UnoVsUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnoVsUnoActionPerformed(evt);
            }
        });
        getContentPane().add(UnoVsUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 270, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocotris/HomeTris.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 410));

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 246, 90, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UnoVsUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnoVsUnoActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        VsUno v = new VsUno();
        v.setVisible(true);
    }//GEN-LAST:event_UnoVsUnoActionPerformed

    private void UnoVsPcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnoVsPcActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        VsPc v = new VsPc();
        v.setVisible(true);
    }//GEN-LAST:event_UnoVsPcActionPerformed

    private void SettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        SettingPage v = new SettingPage();
        v.setVisible(true);
    }//GEN-LAST:event_SettingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Setting;
    private javax.swing.JButton UnoVsPc;
    private javax.swing.JButton UnoVsUno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
