package giocotris;

import java.util.Random;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Niccolo'
 */
public class VsUno extends javax.swing.JFrame {
    /**
     * Creates new form UnoVsUno
     */
    public VsUno() {
        initComponents();
    }
    private int[][] tris;
    private int currentPlayer;
    
    Random random = new Random();
     

        

    public void startGame(int player){
        
    }
    public void inizializzaMatrice(){
        currentPlayer = random.nextInt(2);
        for (int i = 0; i < 3; i++) {
                for (int j = 0; j < 3; j++) {
                    tris[i][j] = 0;
                }
            }
    }
    public boolean isBoardFull() {
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                if (tris[i][j] == 0) {
                    return false;
                }
            }
        }
        return true;
    }

    public boolean checkForWin() {
        return (checkRowsWin() || checkColumnsWin() || checkDiagonalsWin());
    }

    private boolean checkRowsWin() {
        for (int i = 0; i < 3; i++) {
            if (checkRowCol(tris[i][0], tris[i][1], tris[i][2])) {
                return true;
            }
        }
        return false;
    }

    private boolean checkColumnsWin() {
        for (int i = 0; i < 3; i++) {
            if (checkRowCol(tris[0][i], tris[1][i], tris[2][i])) {
                return true;
            }
        }
        return false;
    }

    private boolean checkDiagonalsWin() {
        return ((checkRowCol(tris[0][0], tris[1][1], tris[2][2])) ||
                (checkRowCol(tris[0][2], tris[1][1], tris[2][0])));
    }

    private boolean checkRowCol(int c1, int c2, int c3) {
        if ( c1==c2 && c2 == c3 && c2!=0){
            return true;
        }else{
            return false;
        }
    }

    private void resetBoard() {
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
              /*  jLabel1.setIcon(false);
                jLabel1.setIcon(false);
                jLabel3.setIcon(false);
                jLabel4.setIcon(false);
                jLabel5.setIcon(false);
                jLabel6.setIcon(false);
                jLabel7.setIcon(false);
                jLabel8.setIcon(false);
                jLabel9.setIcon(false);
            }*/
        }
    }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1273, 720));
        setMinimumSize(new java.awt.Dimension(1273, 720));
        setPreferredSize(new java.awt.Dimension(1273, 720));

        jPanel1.setMaximumSize(new java.awt.Dimension(1273, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1273, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giocotris/base.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1273, 720));
        jLabel1.setMinimumSize(new java.awt.Dimension(1273, 720));
        jLabel1.setPreferredSize(new java.awt.Dimension(1273, 720));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1273, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VsUno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VsUno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VsUno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VsUno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VsUno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
